FROM python:3.12-slim
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app
COPY pyproject.toml .
RUN uv sync --group controller

COPY src/controller.py .
EXPOSE 8080

CMD ["uv", "run", "controller.py"]