# controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-controller
  template:
    metadata:
      labels:
        app: job-controller
    spec:
      serviceAccountName: job-controller-sa
      containers:
      - name: controller
        image: localhost/k8s-jaas-controller:1.1
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: job-controller-service
spec:
  selector:
    app: job-controller
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer
---
# RBAC permissions for controller to create jobs
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-controller-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-controller-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-controller-binding
subjects:
- kind: ServiceAccount
  name: job-controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: job-controller-role
  apiGroup: rbac.authorization.k8s.io